#!/bin/sh
if [ -z "$1" ]; then
    echo "Usage: doforallgit <command>"
    exit 1
fi

start_folder=$PWD
for D in `find . -maxdepth 1 -type d`
do
    cd $start_folder/$D
    if test -d ".git" || test -f ".git"; then
        echo "---- In: $D ----"
        echo "Doing $*"
        $*
    else
        echo "$D is not a git directory so skipping"
    fi
    cd $start_folder
done
exit 0

