#!/bin/sh
if [ "$#" -ne 2 ]; then
    echo "Usage: gittagfordate <date> <tag>"
    exit 1
fi



start_folder=$PWD
for D in `find . -maxdepth 1 -type d -printf %f\\\\n`
do
    cd $start_folder/$D
    if test -d ".git" || test -f ".git"; then
        echo "---- In: $D ----"
        F=`git log -n 1 --format=%H --until=$1`
        echo "Tagging commit $F as $2"
        git tag $2 $F
    else
        echo "$D is not a git directory so skipping"
    fi
    cd $start_folder
done
    

echo "Done"
exit 0
